### ISSUE TITLE
Trying to understand how it works...

### ISSUE THREAD

**Issue by fewerjunk** [hophead-ninja/perfect_select#1]
Attached is the blend file.

I want to take the other object and add it as a shape to a face (each) face of the dodecahedron.

What i've tried isn't working.  Looked at the demo using Suzanne.

Likely I'm doing something wrong.

Dodec / GRiD - GRiD Front on Face of Dodec (I think)
https://pasteall.org/blend/4ac11a25e025411b9e8807dfbe37dfaf

**Comment by hoppy-tools** [comment]
Hey, 

This is a selection tool, you must have some geometry to select, you can try to subdivide face, and next select inner faces/elements.

**Comment by fewerjunk** [comment]
Now, why didn’t I think of that. /s

**Comment by fewerjunk** [comment]
Here’s the object.  Self explanatory - GRiD to Cube.

Tried as suggested.

Didn’t work.

So, I’m trying to understand how it works, cuz, what I tried, didn’t work.

Better?

https://pasteall.org/blend/648eb0d45d824fb690ac657114e5870e

**Comment by hoppy-tools** [comment]
The same situation, you don't have enough geometry.

https://pasteall.org/blend/a51ee836d047471fbc68e905da1a6141

**Comment by fewerjunk** [comment]
I followed the directions.  Added more mesh.  Circle select (Try 1).  Object select (Try 2) - selected object, Blender crashed.

MacBook - 32 GB memory, Radeon 8 GB Graphics Card, 2 TB SSD HD.

It may or may not be your addon.

Settings:  Remesh, GRiD, Sharp, Octree Depth: 7, Remove Disconnected: Unchecked

Cube: Subdivide: 100

Octahedron:

Same Remesh. Cube: Subdivide: 50

Same result.

**Comment by fewerjunk** [comment]
Correction:  Addon crashed, not Blender.

**Comment by hoppy-tools** [comment]
Unfortunately I don't have access to any macbook to reproduce it. I repeated it on a 6 year old PC with linux (16GB memory) and I have no crash. When I've the opportunity I will investigate it.

**Comment by fewerjunk** [comment]
Biggest mistake was buying a MacBook Pro.  Couldn’t find a decent linux capable laptop with similar specs.

I paid more attention to the hype.

First mistake.

I’ve had fewer problems, more possibilities on the Linux laptops I’ve run for me as well as my wife than using MacBook (currently: Big Sur).

**Comment by fewerjunk** [comment]
My wife’s laptop:  Linux Mint (Latest), 8 GB memory, I5 - no problems.  Same settings.  Same test.

Will try on my macbook, using my wife’s login (less overhead).

**Comment by fewerjunk** [comment]
Same behavior on MacBook logged in as my wife.


That it works on a Laptop with Linux Mint, less memory, less storage, says there’s a problem that may not be resource related.

Otherwise, why work on my wife’s laptop with fewer resources but not mine?

**Comment by hoppy-tools** [comment]
OK, anyway in the next version I will try to get mac and add full support. Thanks for the report.
